### ISSUE TITLE
Text with link in Bottom Dialog

### ISSUE THREAD

**Issue by jessegpierce** [dxx/mcx-dialog-mobile#12]
Thank you for your plugin. I can't seem to get a hyperlink working in the Bottom Dialog in pure javascript. I'm using it as a map attribution action sheet. Is it possible? Something like
`//Attribute "i" button click
jQuery(function($) {
    $("#attrContainer").on("click", function() {
        mcxDialog.showBottom({
				btn: ["<a href=\'https://www.mapbox.com/about/maps/\'>© Mapbox</a>",
						"<a href=\'http://www.openstreetmap.org/copyright\'>© OpenStreetMap</a>",
						"<a href=\'https://www.mapbox.com/map-feedback/\' target=\'_blank\'><strong>Improve this map</strong>"],  // Setting button text
				btnColor: ["#448cd4", "#448cd4"]  // Setting button text color
			});
    })
})`

**Comment by jessegpierce** [comment]
I ended up doing this:
`btnClick: function(index){
					//alert("You clicked" + btn[index - 1]);
					if (btn[index - 1] === "© Mapbox") {
						window.location.href = 'https://www.mapbox.com/about/maps/';
					} else if (btn[index - 1] === "© OpenStreetMap") {
						window.location.href = 'http://www.openstreetmap.org/copyright';
						} else if (btn[index - 1] === "Improve this map") {
							window.location.href = 'https://www.mapbox.com/map-feedback/';
						}
				}`

**Comment by dxx** [comment]
Good job!
